### ISSUE TITLE
Array parameter issue in Incidents api

### ISSUE THREAD

**Issue by dorony** [PagerDuty/pagerduty-api-python-client#1]
The following code fails with an error:
`pypd.Incident.find(statuses=['triggered', 'acknowledged'])`
And the error is:
`BadRequest: BadRequest (2001): Invalid Input Provided - Statuses must be in triggered, acknowledged, or resolved.`
It works when passing just one value in the array so I suspect there's a problem with the url generated for the request when an array has more than one item.

**Comment by Havelock-Vetinari** [comment]
This should fix your issue with multiple values in kwargs.
BTW, this project os howling for tests ;-)

**Comment by jdcumpson** [comment]
Please accept my apologies for being *so* late to this issue. Somehow I unsubbed from my own project. At any rate, I'll verify the fix and maybe even make a new test for this today. Thanks so much for your contributions :) please feel free to bug me about it.
