### ISSUE TITLE
API feedback - create

### ISSUE THREAD

**Issue by rbtcollins** [PagerDuty/pagerduty-api-python-client#14]
it might be nice to have a modelled-in-Python version of objects.

E.g. rather than passing a free form dict to create(), pass in an EscalationSchedule object, which would allow things like 'help()' to work locally rather than having to dig up the v2 API docs from online and then translating that to Python - having to guess what needs to be supplied, and whats mandatory etc.

**Comment by jdcumpson** [comment]
Yep, that's kind of what the models are all about - however, I purposely only have added models that are officially supported by the v2 documentation as endpoints. What could be a win/win would is:

```
class EscalationPolicy(...):
    """
    Some up-to-date-docs.

    The data parameter expects a dictionary like:
    {'schedule': 
        ...
     }
    """
   ...


help(EscalationPolicy) 
```
       
 There's also `validate` class method which does the assertion perhaps the documentation from that function could be borrowed somehow.

Probably least amount of work and best practice to just be better at making docs than enforcing another abstraction.

**Comment by bzmw** [comment]
Hey there, 
Thanks for your contribution but we decided to deprecate this project. Please use [PDPyras](https://github.com/PagerDuty/pdpyras) instead.
