### ISSUE TITLE
Support Alerts

### ISSUE THREAD

**Issue by calebsmac** [PagerDuty/pagerduty-api-python-client#19]
One major feature this library appears to be currently missing is Pagerduty Alerts ([API reference](https://v2.developer.pagerduty.com/v2/page/api-reference#!/Incidents/get_incidents_id_alerts))

This is important because we often include important information in the event body, which is not available from the incident or log message APIs.

Any thoughts on potential implementation?

**Comment by jdcumpson** [comment]
Hey @calebsmac thanks for joining in on the fun. It's true that `Alerts` weren't the thing they are today when this was first cooked up. I'd like to see alerts become a first class model much in the same way log entries are. In fact, they probably can have a very similar implementation. I would start with looking at how `LogEntry` is used - and see if that can be replicated.

`LogEntry` may need some love too. Thanks for pointing it out!
