### ISSUE TITLE
Mechanism to set the proxy

### ISSUE THREAD

**Issue by lee-kode** [PagerDuty/pagerduty-api-python-client#25]
Hi,
First, I'd like to say thank you for creating this module. It's been helpful.

I have found an issue. There is no mechanism (in the docs or the code) where I could easily set the proxies for requests to consume. Do you have plans for this? If not right now, would you mind me trying my hand and submitting a pull request?

Thank you.

Lee

**Comment by jdcumpson** [comment]
@lee-kode hello! Thanks for bringing this up. It's actually something I hadn't even started to address. Your PR would be most welcome, and thanks for bringing up the issue. By all means give it a go! You can ask any questions here too if you need to :)

**Comment by lee-kode** [comment]
Pull request: https://github.com/PagerDuty/pagerduty-api-python-client/pull/29

**Comment by lee-kode** [comment]
Pull request #29 has been merged so I guess this issue can be closed?

**Comment by jdcumpson** [comment]
Oh, yep! Thanks again @lee-kode 👍
