### ISSUE TITLE
Support setting API key from environment variable

### ISSUE THREAD

**Issue by swarren83** [PagerDuty/pagerduty-api-python-client#36]
Setting sensitive data via file is not optimal when using docker containers.  This is because a docker container is built in layers and the file will be available in the layer even if deleted.  Allowing anyone with access to the docker image to be able to acquire the sensitive data(API key).

It is best practice to set environment variables, at container runtime, for sensitive data that will be passed to a docker container.

**Comment by bzmw** [comment]
Hey there, 
Thanks for your contribution but we decided to deprecate this project. Please use [PDPyras](https://github.com/PagerDuty/pdpyras) instead.
