### ISSUE TITLE
pip install?

### ISSUE THREAD

**Issue by papaben** [PagerDuty/pagerduty-api-python-client#4]
Hi,

This library looks great. I'd love to start using it. What are your recommendations for installation? I can't find `pypd` in pip. Also, the URL in `setup.py` has the wrong URL for GitHub. 

Sincerely,
Ben

**Comment by gwillem** [comment]
`pip install -e git+https://github.com/PagerDuty/pagerduty-api-python-client.git#egg=pypd`

**Comment by papaben** [comment]
Ok, great. Thank you.
