### ISSUE TITLE
Is there an example for creating an integration with a service Id?

### ISSUE THREAD

**Issue by btsteve** [PagerDuty/pagerduty-api-python-client#40]
I am trying to create an integration on a service I just created through the API. The service creation portion is working great. I can not seem to pass the correct info into the create_integration method.

**Comment by tom-aa** [comment]
same question here

**Comment by tom-aa** [comment]
https://github.com/PagerDuty/API_Python_Examples/blob/master/REST_API_v2/Services/create_integration.py

**Comment by tom-aa** [comment]
@btsteve

**Comment by snemetz** [comment]
Creating a V1 integration with pypd is:
```
            data = {
                "type": "generic_events_api_inbound_integration",
                "name": "Service Monitor",
                "service": {
                  "id": service_id,
                  "type": "service_reference"
                 }
            }
            pypd.Integration.create(service=service_id, data=data)

```
Not sure if it can be made to do v2

**Comment by bzmw** [comment]
Hey there, 
Thanks for your contribution but we decided to deprecate this project. Please use [PDPyras](https://github.com/PagerDuty/pdpyras) instead.
