### ISSUE TITLE
How to set include parameter?

### ISSUE THREAD

**Issue by sciurus** [PagerDuty/pagerduty-api-python-client#41]
Pagerduty lets you including additional data in response from some endpoints via an `include[]` query parameter. E.G. `https://api.pagerduty.com/services?time_zone=UTC&sort_by=name&include%5B%5D=integrations` to get more details on each services' integrations.

pypd support  passing arbitrary query parameters as kwargs to `find`. However,  neither `include[]` nor `include%5B%5D` is a valid variable name in python, so this will not work.

**Comment by bzmw** [comment]
Hey there, 
Thanks for your contribution but we decided to deprecate this project. Please use [PDPyras](https://github.com/PagerDuty/pdpyras) instead.
