### ISSUE TITLE
find_name with equal comparison seems not do exactly match 

### ISSUE THREAD

**Issue by QingsongYao** [PagerDuty/pagerduty-api-python-client#45]
Tried following query:
pypd.Schedule.find_one(name='Canaveral T').json
{u'name': u'Canaveral Tier 1', u'self': u'

The name does not exactly match

**Comment by bzmw** [comment]
Hey there, 
Thanks for your contribution but we decided to deprecate this project. Please use [PDPyras](https://github.com/PagerDuty/pdpyras) instead.
