### ISSUE TITLE
Don't send API key header when none exists

### ISSUE THREAD

**Issue by seantsb** [PagerDuty/pagerduty-api-python-client#48]
I am creating events using service Integration Keys (which have very restricted permission sets) rather than the API key (which has full permissions). However, the `ClientMixin.request` code does the following

```python
        auth = 'Token token={0}'.format(self.api_key)
        if headers is None:
            headers = {
                'Accept': CONTENT_TYPE,
                'Authorization': auth,
                'Content-Type': 'application/json',
            }
```
which works but sends an invalid auth token (`token=None`). The token should be omitted if it's `None` since I imagine they could stop supporting this and reject the event entirely.

**Comment by bzmw** [comment]
Hey there, 
Thanks for your contribution but we decided to deprecate this project. Please use [PDPyras](https://github.com/PagerDuty/pdpyras) instead.
