### ISSUE TITLE
Plans for Python 3 support?

### ISSUE THREAD

**Issue by gwillem** [PagerDuty/pagerduty-api-python-client#5]
Thanks for sharing this code. It was written for Python 2 though, which seems odd in this era.

**Comment by rbtcollins** [comment]
+1 - we're Python3 only, so this is a bit of an issue.

**Comment by jdcumpson** [comment]
It's the python that comes default installed on more OS's. However @rbtcollins made a sweet PR that fixes it. I'll merge it as soon as possible :) Thanks for bring it up.

**Comment by jdcumpson** [comment]
Merged #10! Thanks Robert!
