### ISSUE TITLE
Support Event Rules API

### ISSUE THREAD

**Issue by beli-sk** [PagerDuty/pagerduty-api-python-client#52]
I'm trying to add support for (beta version of) Event Rules to this module, but seems that Event Rules API is inconsistent with the other API endpoints in that the top level key "rules" of the returned JSON is not equal to the endpoint in API URI "event_rules", so that instead of just creating a class `class EventRule(Entity): pass`, I need to override some methods to adapt to this case.

So my question is, do you suggest to use this workaround (I could create a PR when I get it ready) or do you plan to align the Event Rules API endpoint with the rest of the API?

**Comment by tomgoren** [comment]
@beli-sk, I have a feeling you're better off working around anything dependent on updates to this repo - the maintainers seem to be quite busy at the moment.

I'm not trying to be flippant or aggressive, just calling it like I see it.

**Comment by bzmw** [comment]
Hey there, 
Thanks for your contribution but we decided to deprecate this project. Please use [PDPyras](https://github.com/PagerDuty/pdpyras) instead.
