### ISSUE TITLE
New PyPI release?

### ISSUE THREAD

**Issue by tomgoren** [PagerDuty/pagerduty-api-python-client#54]
@PagerDuty It would be nice if the the latest version of `pypd` was available on PyPI (https://pypi.org/project/pypd/#history).

Thanks!

**Comment by melbaa** [comment]
+1

Please bump the version number too.

**Comment by punkrokk** [comment]
any updates on when this might happen?

**Comment by bzmw** [comment]
Hey there, 
Thanks for your contribution but we decided to deprecate this project. Please use [PDPyras](https://github.com/PagerDuty/pdpyras) instead.
