### ISSUE TITLE
Pagination support?

### ISSUE THREAD

**Issue by rbren** [PagerDuty/pagerduty-api-python-client#55]
Sorry if I missed it somewhere, but I don't see any docs/examples for pagination. It looks like you need access to the original JSON response to paginate properly (using the `limit`/`offset`/`total`/`more` fields), and it doesn't _seem_ to be sufficient to just paginate until zero items are returned.

What's the right way to do this?

**Comment by bzmw** [comment]
Hey there, 
Thanks for your contribution but we decided to deprecate this project. Please use [PDPyras](https://github.com/PagerDuty/pdpyras) instead.
