### ISSUE TITLE
SEVERITY_TYPES does not match V2 Events Documentation

### ISSUE THREAD

**Issue by schmiddy** [PagerDuty/pagerduty-api-python-client#56]
The [`SEVERITY_TYPES`](https://github.com/PagerDuty/pagerduty-api-python-client/blob/f420b34ca9b29689cc2ecc9adca6dc5d56ae7161/pypd/models/event.py#L60) defined for `EventV2` are in all-lowercase. There is [an assertion](https://github.com/PagerDuty/pagerduty-api-python-client/blob/f420b34ca9b29689cc2ecc9adca6dc5d56ae7161/pypd/models/event.py#L73) forcing the caller to pass this value in lowercase as well.

But the [Events API V2 documentation](https://v2.developer.pagerduty.com/docs/events-api-v2) claims:

| Field | Examples |
| ---- | ---- |
| Severity |  Enum {**Info, Warning, Error, Critical**} |

i.e. the documentation claims the severity field should be Propercase. 

I believe the documentation and the code should be aligned here. Perhaps the `payload['severity']` input could be coerced with `.lower()` to allow mixed-case input strings, or that doc page could stick with lowercase in its example.

**Comment by bzmw** [comment]
Hey there, 
Thanks for your contribution but we decided to deprecate this project. Please use [PDPyras](https://github.com/PagerDuty/pdpyras) instead.
