### ISSUE TITLE
Is it possible to get logs created after a specified date.

### ISSUE THREAD

**Issue by sanjitab** [PagerDuty/pagerduty-api-python-client#64]
I am planning to create an incremental load ETL process for LogEntry data . As this data is insert only and will not get modified, I can use 'created_at' to limit the data I pull every time. 

pypd.LogEntry.find(created_at > '2019-10-14T22:43:20Z')

Greater than does not work in this case. Is there any other way to get the logs for a limited duration?

**Comment by bzmw** [comment]
Hey there, 
Thanks for your contribution but we decided to deprecate this project. Please use [PDPyras](https://github.com/PagerDuty/pdpyras) instead.
