### ISSUE TITLE
Support for Tags

### ISSUE THREAD

**Issue by damoun** [PagerDuty/pagerduty-api-python-client#65]
Hi,

This module doesn't support Tags and I would like to use tags on user to enrich our oncall reports.
https://api-reference.pagerduty.com/#!/Contextual_Search/get_tags

Do you think it would be possible to update this official pagerduty python module ?

**Comment by crosbymichael1** [comment]
Hi @damoun , I have addressed your concern and once my Pull Request is Merged you will be able to pull tags using this module.

PR: adding support for retrieving Tags #69

**Comment by bzmw** [comment]
Hey there, 
Thanks for your contribution but we decided to deprecate this project. Please use [PDPyras](https://github.com/PagerDuty/pdpyras) instead.
