### ISSUE TITLE
Entity.put() is ignoring the data parameter

### ISSUE THREAD

**Issue by mitjabez** [PagerDuty/pagerduty-api-python-client#66]
PUT requests don't work. Data param is ignored when making the request.

Documentation is also wrong:

```
Delete an entity from the server by ID.
```

**Comment by bzmw** [comment]
Hey there, 
Thanks for your contribution but we decided to deprecate this project. Please use [PDPyras](https://github.com/PagerDuty/pdpyras) instead.
