### ISSUE TITLE
Enable support for rulesets

### ISSUE THREAD

**Issue by sumanshil** [PagerDuty/pagerduty-api-python-client#67]
Update code to support the following APIs.

https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1rulesets/post

**Comment by sumanshil** [comment]
Created this pull request for this issue https://github.com/PagerDuty/pagerduty-api-python-client/pull/68. Can someone please review? Thanks

**Comment by bzmw** [comment]
Hey there, 
Thanks for your contribution but we decided to deprecate this project. Please use [PDPyras](https://github.com/PagerDuty/pdpyras) instead.
