### ISSUE TITLE
find for Teams, Schedules return all available instead of search

### ISSUE THREAD

**Issue by sjtarik** [PagerDuty/pagerduty-api-python-client#7]
When feed with id or name, Teams and Schedules find method return all existing ones instead of querying with parameter. Is that expected behavior? I am able to get particular items with fetch but find not filtering for me for passed parameters.

**Comment by jdcumpson** [comment]
Sorry about the delay. Thanks for reporting, fixed in https://github.com/PagerDuty/pagerduty-api-python-client/commit/91e53fe413c35e3330b7508d8116ac3ea791aad7
