### ISSUE TITLE
Package not published on PyPI

### ISSUE THREAD

**Issue by rbtcollins** [PagerDuty/pagerduty-api-python-client#8]
The standard distribution mechanism for Python packages is to publish to PyPI - this is very straight forward, docs are https://packaging.python.org/distributing/

**Comment by jdcumpson** [comment]
You're totally right. Thanks for the push in the right direction!

**Comment by jodylent** [comment]
+1. My organization is actively looking at this, and the only major stopping point is the lack of easy `pip install pypd`

**Comment by jdcumpson** [comment]
I'll try to focus on this as I'm the one who has to do this versus other code changes. I'll ping back when it's done.

**Comment by lukaslozovski** [comment]
Hey JD,

Any news on publishing this client on pypi?

**Comment by jdcumpson** [comment]
@lukaslozovski 🎉  https://pypi.python.org/pypi/pypd/0.1.0

**Comment by jdcumpson** [comment]
If there are issues with the pypi implementation, make a new issue! I'll get it up to date.
